export const texts = [
    "Write clean code and future you will thank you.",
    "Commit early, commit often, and push with care.",
    "Unit tests are living documentation for your code.",
    "Naming things well is half the battle in software.",
    "A pull request should tell a clear, short story.",
    "Keep functions small; big ones hide big bugs.",
    "Read error messages—they usually show the fix.",
    "Git rebase keeps history tidy but use it wisely.",
    "Type safety turns many runtime errors into compile-time hints.",
    "Automate the boring parts before they bore you.",
    "A failing test is a guide, not a verdict.",
    "Continuous Integration catches issues sooner.",
    "Linting tools teach style through gentle warnings.",
    "Logs are the black box recordings of your app.",
    "Measure performance, then optimise what matters.",
    "Code reviews spread knowledge across the team.",
    "Magic numbers hide intent; use constants instead.",
    "Document why, not just how, in your README.",
    "Containers make “it works on my machine” obsolete.",
    "Feature flags let you ship code safely in small steps.",
    "An interface describes behaviour, not implementation.",
    "Avoid premature optimisation; clarity comes first.",
    "Refactoring is investing in your codebase’s health.",
    "Write once, run anywhere, debug everywhere—embrace it.",
    "Edge cases are users too, so handle them kindly.",
    "A database index is a performance superpower.",
    "Latency hides in network calls; keep them few.",
    "State management is easier when state is predictable.",
    "Descriptive commit messages help archaeology later.",
    "Null is a value; treat it with respect.",
    "Immutable data leads to simpler mental models.",
    "APIs are contracts; breaking changes break trust.",
    "Race conditions love sleeping testers—automate them.",
    "Environment variables separate code from config.",
    "Semantic versioning sets clear upgrade expectations.",
    "Dependency injection decouples and eases testing.",
    "Code without logging is like flying blind at night.",
    "Keyboard shortcuts save minutes that add up to days.",
    "A monorepo simplifies sharing code across services.",
    "Event-driven design scales when work is decoupled.",
    "Caching trades memory for speed—expire wisely.",
    "Version control is the engineer’s time machine.",
    "Feature branches isolate work and reduce conflicts.",
    "Dockerfiles are executable architecture diagrams.",
    "A good README greets new contributors at the door.",
    "Enums express intent better than raw strings.",
    "REST is a style; GraphQL is a language—pick what fits.",
    "Accessibility is not optional; build inclusive UIs.",
    "Tech debt accrues interest—pay it down regularly.",
    "Pair programming turns tacit knowledge into shared skill.",
    "Shipping beats perfection when feedback is fast."
  ] as const; // ← 配列内容を完全リテラル型に固定
  